language:
  - ruby
rvm:
  - 2.0.0
env:
  - RAILS_VERSION=4.0.0
gemfile:
  - Gemfile

install:
  - rvm gemset list
  - bundle install
  - rake db:create
  - rake db:migrate
  - rake db:seed
before_script:
  - source ~/.rvm/scripts/rvm
  - type rvm | head -n 1
  - bash start_local_billit.bash
  - rvm gemset use default
  - bash start_local_writeit.bash
  - start_local_popit_api.bash
  #- start_local_writeit.bash
  # creating database
  # creating default admin user
