language:
  - ruby
rvm:
  - 2.0.0
env:
  - RAILS_VERSION=4.0.0
gemfile:
  - Gemfile
before_script:
  - sudo apt-get install virtualenv
  - bash start_local_writeit.bash
  - start_local_popit_api.bash
  #- start_local_writeit.bash
  # updating bundle environment
  - bundle install --without production
  # creating database
  - rake db:create
  - rake db:migrate
  # creating default admin user
  - rake db:seed
