production:
  root_url:   "cabildo.production-site.org"
  billit:     "billit.production-site.org"
  popit:		  "popit.production-site.org"
  tables:     "http://pmo.apidone.com/tables"
  writeit:    ~
  scout:      ~
  analytics:  "UA-XXXXX-X"
  disqus_shortname:     ~
  parliaments-initial-date: "1990-03-01"

development:
  root_url:   "http://beta.votainteligente.cl/"
  billit:     "http://billit.ciudadanointeligente.org/bills/"
  popit:      "http://billit-demo.popit.mysociety.org/"
  tables:     "http://pmo.apidone.com/tables"
  writeit:    ~
  scout:      ~
  analytics:  ~
  disqus_shortname:   ~
  parliaments-initial-date: "1990-03-01"

test:
  root_url:   "cabildo.test-site.org"
  billit:     "http://billit.ciudadanointeligente.org/bills/"
  popit:      "popit.test-site.org"
  tables:     "http://table.com"
  writeit:    ~
  scout:      ~
  analytics:  ~
  disqus_shortname:     ~
  parliaments-initial-date: "1990-03-01"
