# Legislative - Public setting file

# If you want customize the project settings, do it in the private_legislative.yml file.
# The values in that file override the values that are below.

production:
  root_url:   ~
  billit:     ~
  popit_url: ~
  popit_persons:  ~
  popit_search: ~
  tables:     ~
  writeit:    ~
  scout:      ~
  analytics:  ~
  disqus_shortname:   ~
  disqus_language:    ~
  disqus_developer:   '0'
  bill_graph_data_length: '12'
  bill_graph_day_interval: '7'
  parliaments-initial-date: '1990-03-01'

development:
  root_url:   ~     #example: 'http://www.congresodechile.cl/'; used for links in the exported XLS files
  billit:     ~     #example: 'http://billit-instance.org/bills/'; for more info about this POPLUS component check https://github.com/ciudadanointeligente/bill-it
  popit_url:  ~     #example: 'legislative-instance.popit.mysociety.org'; you will need create a instance, please contact with mysociety's popit team in popit@mysociety.org. http://popit.mysociety.org/instances/new
  popit_persons:  ~ #example: 'http://legislative-instance.popit.mysociety.org/api/v0.1/persons/'; the same instance used above but with http and person path
  popit_search: ~   #example: 'http://legislative-instance.popit.mysociety.org/api/v0.1/search/persons?'; used for person search
  tables:     ~     #example: 'http://pmo.apidone.com/tables/tables'; temporal resource, is an array of tables, inside has bills. [WIP]
  writeit:    ~     #Unused in this moment, for more info about this POPLUS component check https://github.com/ciudadanointeligente/write-it
  scout:      ~     #Unused in this moment, for more info about this app check https://github.com/sunlightlabs/scout
  analytics:  ~     #Google Analytics code
  disqus_shortname:   ~     #Disqus identifier, to manage comments in Disqus you will need a account. https://disqus.com/admin/signup/
  disqus_language:    ~     #example: 'ru'; For a full list of supported languages https://www.transifex.com/projects/p/disqus/
  disqus_developer:   '1'   #Use '1' for local testing, otherwise use '0'
  bill_graph_data_length: '12'  # amount of points in the graph
  bill_graph_day_interval: '7'  # amount of days per point in graph
  parliaments-initial-date: '1990-03-01'   #The initial date for bill search purposes

test:
  root_url:   ~
  billit:     'http://127.0.0.1.xip.io:3003/bills/'
  popit_url: 'billit-demo.popit.mysociety.org'
  popit_persons:  'http://localhost:3002/api/persons/'
  popit_search: 'http://localhost:3002/api/search/persons?'
  tables:     'http://pmo.apidone.com/tables'
  writeit:    ~
  scout:      ~
  analytics:  ~
  disqus_shortname:   ~
  disqus_language:    ~
  disqus_developer:   '0'
  bill_graph_data_length: '12'
  bill_graph_day_interval: '7'
  parliaments-initial-date: '1990-03-01'
