# Legislative - Public setting file

# If you want customize the project settings, do it in the private_legislative.yml file.
# The values in that file override the values that are below.

production:
  root_url:   ~
  analytics:  ~
  disqus_shortname: ~
  disqus_language:  ~
  disqus_developer: '0'
  bill_graph_data_length:   '12'
  bill_graph_day_interval:  '7'
  parliaments_initial_date: '1990-03-01'
  billit_url: ~
  paperworks_url: 'http://billit.ciudadanointeligente.org/paperworks/'
  popit_url:  ~
  popit_persons: ~
  popit_search:  ~
  tables_url:    ~
  writeit_base_url: ~
  writeit_url:      ~
  writeit_username: ~
  writeit_api_key:  ~
  writeit_messages_per_page: '20'

development:
  root_url:   ~           #example: 'http://www.congresoabierto.cl/'; used for links in the exported XLS files
  analytics:  ~           #example: 'UA-XXXXX-X'; Google Analytics code
  disqus_shortname: ~     #example: 'qwerty'; Disqus identifier, to manage comments in Disqus you will need a account. https://disqus.com/admin/signup/
  disqus_language:  ~     #example: 'ru'; For a full list of supported languages https://www.transifex.com/projects/p/disqus/
  disqus_developer: '1'   #Use '1' for local testing, otherwise use '0'
  bill_graph_data_length:   '12'  # amount of points in the graph
  bill_graph_day_interval:  '7'   # amount of days per point in graph
  parliaments_initial_date: '1990-03-01' #The initial date for bill search purposes
  billit_url: ~       #example: 'http://billit-instance.org/bills/'; for more info about this POPLUS component check https://github.com/ciudadanointeligente/bill-it
  paperworks_url: 'http://billit.ciudadanointeligente.org/paperworks/'
  popit_url:  ~       #example: 'legislative-instance.popit.mysociety.org'; you will need create a instance, please contact with mysociety's popit team in popit@mysociety.org. http://popit.mysociety.org/instances/new
  popit_persons:  ~   #example: 'http://legislative-instance.popit.mysociety.org/api/v0.1/persons/'; the same instance used above but with http and person path
  popit_search:   ~   #example: 'http://legislative-instance.popit.mysociety.org/api/v0.1/search/persons?'; used for person search
  tables_url:     ~   #example: 'http://pmo.apidone.com/tables/tables'; temporal resource, is an array of tables, inside has bills. [WIP]
  writeit_base_url: ~ #example: 'http://localhost:3001'; you will need create a instance, please contact with ciudadanointeligente's lab team in lab@ciudadanointeligente.org. http://writeit.ciudadanointeligente.org/
  writeit_url:      ~ #example: '/api/v1/instance/2/'; writeit instance path
  writeit_username: ~ #example: 'admin'; writeit username
  writeit_api_key:  ~ #example: 'a'; writeit apikey
  writeit_messages_per_page: '20'

test:
  root_url:  ~
  analytics: ~
  disqus_shortname: ~
  disqus_language:  ~
  disqus_developer: '0'
  bill_graph_data_length:   '12'
  bill_graph_day_interval:  '7'
  parliaments_initial_date: '1990-03-01'
  billit_url: 'http://127.0.0.1.xip.io:3003/bills/'
  paperworks_url: 'http://billit.ciudadanointeligente.org/paperworks/'
  popit_url:  'localhost:3002'
  popit_persons:  'http://localhost:3002/api/persons/'
  popit_search:   'http://localhost:3002/api/search/persons?'
  tables_url:     'http://pmo.apidone.com/tables'
  writeit_base_url: 'http://localhost:3001'
  writeit_url:      '/api/v1/instance/1/'
  writeit_username: 'admin'
  writeit_api_key:  'a'
  writeit_messages_per_page: '20'
